/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RankingByTradeVolumeResponseRanking
    /// </summary>
    [DataContract(Name = "RankingByTradeVolumeResponse_Ranking")]
    public partial class RankingByTradeVolumeResponseRanking : IEquatable<RankingByTradeVolumeResponseRanking>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RankingByTradeVolumeResponseRanking" /> class.
        /// </summary>
        /// <param name="no">順位&lt;br&gt;※ランキング内で同じ順位が返却される場合があります（10位が2件など）.</param>
        /// <param name="trend">トレンド &lt;table&gt;     &lt;thead&gt;         &lt;tr&gt;             &lt;th&gt;定義値&lt;/th&gt;             &lt;th&gt;内容&lt;/th&gt;         &lt;/tr&gt;     &lt;/thead&gt;     &lt;tbody&gt;         &lt;tr&gt;             &lt;td&gt;0&lt;/td&gt;             &lt;td&gt;対象データ無し&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;1&lt;/td&gt;             &lt;td&gt;過去10営業日より20位以上上昇&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;2&lt;/td&gt;             &lt;td&gt;過去10営業日より1～19位上昇&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;3&lt;/td&gt;             &lt;td&gt;過去10営業日と変わらず&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;4&lt;/td&gt;             &lt;td&gt;過去10営業日より1～19位下落&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;5&lt;/td&gt;             &lt;td&gt;過去10営業日より20位以上下落&lt;/td&gt;         &lt;/tr&gt;     &lt;/tbody&gt; &lt;/table&gt;.</param>
        /// <param name="averageRanking">平均順位&lt;br&gt;※100位以下は「999」となります.</param>
        /// <param name="symbol">銘柄コード.</param>
        /// <param name="symbolName">銘柄名称.</param>
        /// <param name="currentPrice">現在値.</param>
        /// <param name="changeRatio">前日比.</param>
        /// <param name="rapidTradePercentage">売買高急増（％）.</param>
        /// <param name="tradingVolume">売買高.</param>
        /// <param name="currentPriceTime">時刻&lt;br&gt;HH:mm&lt;br&gt;※日付は返しません.</param>
        /// <param name="changePercentage">騰落率（%）.</param>
        /// <param name="exchangeName">市場名.</param>
        /// <param name="categoryName">業種名.</param>
        public RankingByTradeVolumeResponseRanking(int no = default(int), string trend = default(string), double averageRanking = default(double), string symbol = default(string), string symbolName = default(string), double currentPrice = default(double), double changeRatio = default(double), double rapidTradePercentage = default(double), double tradingVolume = default(double), string currentPriceTime = default(string), double changePercentage = default(double), string exchangeName = default(string), string categoryName = default(string))
        {
            this.No = no;
            this.Trend = trend;
            this.AverageRanking = averageRanking;
            this.Symbol = symbol;
            this.SymbolName = symbolName;
            this.CurrentPrice = currentPrice;
            this.ChangeRatio = changeRatio;
            this.RapidTradePercentage = rapidTradePercentage;
            this.TradingVolume = tradingVolume;
            this.CurrentPriceTime = currentPriceTime;
            this.ChangePercentage = changePercentage;
            this.ExchangeName = exchangeName;
            this.CategoryName = categoryName;
        }

        /// <summary>
        /// 順位&lt;br&gt;※ランキング内で同じ順位が返却される場合があります（10位が2件など）
        /// </summary>
        /// <value>順位&lt;br&gt;※ランキング内で同じ順位が返却される場合があります（10位が2件など）</value>
        [DataMember(Name = "No", EmitDefaultValue = true)]
        public int No { get; set; }

        /// <summary>
        /// トレンド &lt;table&gt;     &lt;thead&gt;         &lt;tr&gt;             &lt;th&gt;定義値&lt;/th&gt;             &lt;th&gt;内容&lt;/th&gt;         &lt;/tr&gt;     &lt;/thead&gt;     &lt;tbody&gt;         &lt;tr&gt;             &lt;td&gt;0&lt;/td&gt;             &lt;td&gt;対象データ無し&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;1&lt;/td&gt;             &lt;td&gt;過去10営業日より20位以上上昇&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;2&lt;/td&gt;             &lt;td&gt;過去10営業日より1～19位上昇&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;3&lt;/td&gt;             &lt;td&gt;過去10営業日と変わらず&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;4&lt;/td&gt;             &lt;td&gt;過去10営業日より1～19位下落&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;5&lt;/td&gt;             &lt;td&gt;過去10営業日より20位以上下落&lt;/td&gt;         &lt;/tr&gt;     &lt;/tbody&gt; &lt;/table&gt;
        /// </summary>
        /// <value>トレンド &lt;table&gt;     &lt;thead&gt;         &lt;tr&gt;             &lt;th&gt;定義値&lt;/th&gt;             &lt;th&gt;内容&lt;/th&gt;         &lt;/tr&gt;     &lt;/thead&gt;     &lt;tbody&gt;         &lt;tr&gt;             &lt;td&gt;0&lt;/td&gt;             &lt;td&gt;対象データ無し&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;1&lt;/td&gt;             &lt;td&gt;過去10営業日より20位以上上昇&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;2&lt;/td&gt;             &lt;td&gt;過去10営業日より1～19位上昇&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;3&lt;/td&gt;             &lt;td&gt;過去10営業日と変わらず&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;4&lt;/td&gt;             &lt;td&gt;過去10営業日より1～19位下落&lt;/td&gt;         &lt;/tr&gt;         &lt;tr&gt;             &lt;td&gt;5&lt;/td&gt;             &lt;td&gt;過去10営業日より20位以上下落&lt;/td&gt;         &lt;/tr&gt;     &lt;/tbody&gt; &lt;/table&gt;</value>
        [DataMember(Name = "Trend", EmitDefaultValue = true)]
        public string Trend { get; set; }

        /// <summary>
        /// 平均順位&lt;br&gt;※100位以下は「999」となります
        /// </summary>
        /// <value>平均順位&lt;br&gt;※100位以下は「999」となります</value>
        [DataMember(Name = "AverageRanking", EmitDefaultValue = true)]
        public double AverageRanking { get; set; }

        /// <summary>
        /// 銘柄コード
        /// </summary>
        /// <value>銘柄コード</value>
        [DataMember(Name = "Symbol", EmitDefaultValue = true)]
        public string Symbol { get; set; }

        /// <summary>
        /// 銘柄名称
        /// </summary>
        /// <value>銘柄名称</value>
        [DataMember(Name = "SymbolName", EmitDefaultValue = true)]
        public string SymbolName { get; set; }

        /// <summary>
        /// 現在値
        /// </summary>
        /// <value>現在値</value>
        [DataMember(Name = "CurrentPrice", EmitDefaultValue = true)]
        public double CurrentPrice { get; set; }

        /// <summary>
        /// 前日比
        /// </summary>
        /// <value>前日比</value>
        [DataMember(Name = "ChangeRatio", EmitDefaultValue = true)]
        public double ChangeRatio { get; set; }

        /// <summary>
        /// 売買高急増（％）
        /// </summary>
        /// <value>売買高急増（％）</value>
        [DataMember(Name = "RapidTradePercentage", EmitDefaultValue = true)]
        public double RapidTradePercentage { get; set; }

        /// <summary>
        /// 売買高
        /// </summary>
        /// <value>売買高</value>
        [DataMember(Name = "TradingVolume", EmitDefaultValue = true)]
        public double TradingVolume { get; set; }

        /// <summary>
        /// 時刻&lt;br&gt;HH:mm&lt;br&gt;※日付は返しません
        /// </summary>
        /// <value>時刻&lt;br&gt;HH:mm&lt;br&gt;※日付は返しません</value>
        [DataMember(Name = "CurrentPriceTime", EmitDefaultValue = true)]
        public string CurrentPriceTime { get; set; }

        /// <summary>
        /// 騰落率（%）
        /// </summary>
        /// <value>騰落率（%）</value>
        [DataMember(Name = "ChangePercentage", EmitDefaultValue = true)]
        public double ChangePercentage { get; set; }

        /// <summary>
        /// 市場名
        /// </summary>
        /// <value>市場名</value>
        [DataMember(Name = "ExchangeName", EmitDefaultValue = true)]
        public string ExchangeName { get; set; }

        /// <summary>
        /// 業種名
        /// </summary>
        /// <value>業種名</value>
        [DataMember(Name = "CategoryName", EmitDefaultValue = true)]
        public string CategoryName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RankingByTradeVolumeResponseRanking {\n");
            sb.Append("  No: ").Append(No).Append("\n");
            sb.Append("  Trend: ").Append(Trend).Append("\n");
            sb.Append("  AverageRanking: ").Append(AverageRanking).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  SymbolName: ").Append(SymbolName).Append("\n");
            sb.Append("  CurrentPrice: ").Append(CurrentPrice).Append("\n");
            sb.Append("  ChangeRatio: ").Append(ChangeRatio).Append("\n");
            sb.Append("  RapidTradePercentage: ").Append(RapidTradePercentage).Append("\n");
            sb.Append("  TradingVolume: ").Append(TradingVolume).Append("\n");
            sb.Append("  CurrentPriceTime: ").Append(CurrentPriceTime).Append("\n");
            sb.Append("  ChangePercentage: ").Append(ChangePercentage).Append("\n");
            sb.Append("  ExchangeName: ").Append(ExchangeName).Append("\n");
            sb.Append("  CategoryName: ").Append(CategoryName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RankingByTradeVolumeResponseRanking);
        }

        /// <summary>
        /// Returns true if RankingByTradeVolumeResponseRanking instances are equal
        /// </summary>
        /// <param name="input">Instance of RankingByTradeVolumeResponseRanking to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RankingByTradeVolumeResponseRanking input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.No == input.No ||
                    this.No.Equals(input.No)
                ) && 
                (
                    this.Trend == input.Trend ||
                    (this.Trend != null &&
                    this.Trend.Equals(input.Trend))
                ) && 
                (
                    this.AverageRanking == input.AverageRanking ||
                    this.AverageRanking.Equals(input.AverageRanking)
                ) && 
                (
                    this.Symbol == input.Symbol ||
                    (this.Symbol != null &&
                    this.Symbol.Equals(input.Symbol))
                ) && 
                (
                    this.SymbolName == input.SymbolName ||
                    (this.SymbolName != null &&
                    this.SymbolName.Equals(input.SymbolName))
                ) && 
                (
                    this.CurrentPrice == input.CurrentPrice ||
                    this.CurrentPrice.Equals(input.CurrentPrice)
                ) && 
                (
                    this.ChangeRatio == input.ChangeRatio ||
                    this.ChangeRatio.Equals(input.ChangeRatio)
                ) && 
                (
                    this.RapidTradePercentage == input.RapidTradePercentage ||
                    this.RapidTradePercentage.Equals(input.RapidTradePercentage)
                ) && 
                (
                    this.TradingVolume == input.TradingVolume ||
                    this.TradingVolume.Equals(input.TradingVolume)
                ) && 
                (
                    this.CurrentPriceTime == input.CurrentPriceTime ||
                    (this.CurrentPriceTime != null &&
                    this.CurrentPriceTime.Equals(input.CurrentPriceTime))
                ) && 
                (
                    this.ChangePercentage == input.ChangePercentage ||
                    this.ChangePercentage.Equals(input.ChangePercentage)
                ) && 
                (
                    this.ExchangeName == input.ExchangeName ||
                    (this.ExchangeName != null &&
                    this.ExchangeName.Equals(input.ExchangeName))
                ) && 
                (
                    this.CategoryName == input.CategoryName ||
                    (this.CategoryName != null &&
                    this.CategoryName.Equals(input.CategoryName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.No.GetHashCode();
                if (this.Trend != null)
                    hashCode = hashCode * 59 + this.Trend.GetHashCode();
                hashCode = hashCode * 59 + this.AverageRanking.GetHashCode();
                if (this.Symbol != null)
                    hashCode = hashCode * 59 + this.Symbol.GetHashCode();
                if (this.SymbolName != null)
                    hashCode = hashCode * 59 + this.SymbolName.GetHashCode();
                hashCode = hashCode * 59 + this.CurrentPrice.GetHashCode();
                hashCode = hashCode * 59 + this.ChangeRatio.GetHashCode();
                hashCode = hashCode * 59 + this.RapidTradePercentage.GetHashCode();
                hashCode = hashCode * 59 + this.TradingVolume.GetHashCode();
                if (this.CurrentPriceTime != null)
                    hashCode = hashCode * 59 + this.CurrentPriceTime.GetHashCode();
                hashCode = hashCode * 59 + this.ChangePercentage.GetHashCode();
                if (this.ExchangeName != null)
                    hashCode = hashCode * 59 + this.ExchangeName.GetHashCode();
                if (this.CategoryName != null)
                    hashCode = hashCode * 59 + this.CategoryName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
