/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BoardSuccessBuy3
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoardSuccessBuy3Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BoardSuccessBuy3
        //private BoardSuccessBuy3 instance;

        public BoardSuccessBuy3Tests()
        {
            // TODO uncomment below to create an instance of BoardSuccessBuy3
            //instance = new BoardSuccessBuy3();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BoardSuccessBuy3
        /// </summary>
        [Fact]
        public void BoardSuccessBuy3InstanceTest()
        {
            // TODO uncomment below to test "IsType" BoardSuccessBuy3
            //Assert.IsType<BoardSuccessBuy3>(instance);
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }

    }

}
