/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BoardSuccessSell2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoardSuccessSell2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BoardSuccessSell2
        //private BoardSuccessSell2 instance;

        public BoardSuccessSell2Tests()
        {
            // TODO uncomment below to create an instance of BoardSuccessSell2
            //instance = new BoardSuccessSell2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BoardSuccessSell2
        /// </summary>
        [Fact]
        public void BoardSuccessSell2InstanceTest()
        {
            // TODO uncomment below to test "IsType" BoardSuccessSell2
            //Assert.IsType<BoardSuccessSell2>(instance);
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }

    }

}
