/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CommonRankingItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonRankingItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonRankingItems
        //private CommonRankingItems instance;

        public CommonRankingItemsTests()
        {
            // TODO uncomment below to create an instance of CommonRankingItems
            //instance = new CommonRankingItems();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonRankingItems
        /// </summary>
        [Fact]
        public void CommonRankingItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonRankingItems
            //Assert.IsType<CommonRankingItems>(instance);
        }


        /// <summary>
        /// Test the property 'No'
        /// </summary>
        [Fact]
        public void NoTest()
        {
            // TODO unit test for the property 'No'
        }
        /// <summary>
        /// Test the property 'Trend'
        /// </summary>
        [Fact]
        public void TrendTest()
        {
            // TODO unit test for the property 'Trend'
        }
        /// <summary>
        /// Test the property 'AverageRanking'
        /// </summary>
        [Fact]
        public void AverageRankingTest()
        {
            // TODO unit test for the property 'AverageRanking'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'SymbolName'
        /// </summary>
        [Fact]
        public void SymbolNameTest()
        {
            // TODO unit test for the property 'SymbolName'
        }
        /// <summary>
        /// Test the property 'CurrentPrice'
        /// </summary>
        [Fact]
        public void CurrentPriceTest()
        {
            // TODO unit test for the property 'CurrentPrice'
        }
        /// <summary>
        /// Test the property 'ChangeRatio'
        /// </summary>
        [Fact]
        public void ChangeRatioTest()
        {
            // TODO unit test for the property 'ChangeRatio'
        }

    }

}
