/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrdersSuccessDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrdersSuccessDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrdersSuccessDetails
        //private OrdersSuccessDetails instance;

        public OrdersSuccessDetailsTests()
        {
            // TODO uncomment below to create an instance of OrdersSuccessDetails
            //instance = new OrdersSuccessDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdersSuccessDetails
        /// </summary>
        [Fact]
        public void OrdersSuccessDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrdersSuccessDetails
            //Assert.IsType<OrdersSuccessDetails>(instance);
        }


        /// <summary>
        /// Test the property 'SeqNum'
        /// </summary>
        [Fact]
        public void SeqNumTest()
        {
            // TODO unit test for the property 'SeqNum'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'RecType'
        /// </summary>
        [Fact]
        public void RecTypeTest()
        {
            // TODO unit test for the property 'RecType'
        }
        /// <summary>
        /// Test the property 'ExchangeID'
        /// </summary>
        [Fact]
        public void ExchangeIDTest()
        {
            // TODO unit test for the property 'ExchangeID'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'TransactTime'
        /// </summary>
        [Fact]
        public void TransactTimeTest()
        {
            // TODO unit test for the property 'TransactTime'
        }
        /// <summary>
        /// Test the property 'OrdType'
        /// </summary>
        [Fact]
        public void OrdTypeTest()
        {
            // TODO unit test for the property 'OrdType'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
        /// <summary>
        /// Test the property 'ExecutionID'
        /// </summary>
        [Fact]
        public void ExecutionIDTest()
        {
            // TODO unit test for the property 'ExecutionID'
        }
        /// <summary>
        /// Test the property 'ExecutionDay'
        /// </summary>
        [Fact]
        public void ExecutionDayTest()
        {
            // TODO unit test for the property 'ExecutionDay'
        }
        /// <summary>
        /// Test the property 'DelivDay'
        /// </summary>
        [Fact]
        public void DelivDayTest()
        {
            // TODO unit test for the property 'DelivDay'
        }
        /// <summary>
        /// Test the property 'Commission'
        /// </summary>
        [Fact]
        public void CommissionTest()
        {
            // TODO unit test for the property 'Commission'
        }
        /// <summary>
        /// Test the property 'CommissionTax'
        /// </summary>
        [Fact]
        public void CommissionTaxTest()
        {
            // TODO unit test for the property 'CommissionTax'
        }

    }

}
