/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RankingByTickCountResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RankingByTickCountResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RankingByTickCountResponse
        //private RankingByTickCountResponse instance;

        public RankingByTickCountResponseTests()
        {
            // TODO uncomment below to create an instance of RankingByTickCountResponse
            //instance = new RankingByTickCountResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RankingByTickCountResponse
        /// </summary>
        [Fact]
        public void RankingByTickCountResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RankingByTickCountResponse
            //Assert.IsType<RankingByTickCountResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ExchangeDivision'
        /// </summary>
        [Fact]
        public void ExchangeDivisionTest()
        {
            // TODO unit test for the property 'ExchangeDivision'
        }
        /// <summary>
        /// Test the property 'Ranking'
        /// </summary>
        [Fact]
        public void RankingTest()
        {
            // TODO unit test for the property 'Ranking'
        }

    }

}
