/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RankingByMarginResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RankingByMarginResponseAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RankingByMarginResponseAllOf
        //private RankingByMarginResponseAllOf instance;

        public RankingByMarginResponseAllOfTests()
        {
            // TODO uncomment below to create an instance of RankingByMarginResponseAllOf
            //instance = new RankingByMarginResponseAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RankingByMarginResponseAllOf
        /// </summary>
        [Fact]
        public void RankingByMarginResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" RankingByMarginResponseAllOf
            //Assert.IsType<RankingByMarginResponseAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Ranking'
        /// </summary>
        [Fact]
        public void RankingTest()
        {
            // TODO unit test for the property 'Ranking'
        }

    }

}
