/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RankingByCategoryResponseRanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RankingByCategoryResponseRankingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RankingByCategoryResponseRanking
        //private RankingByCategoryResponseRanking instance;

        public RankingByCategoryResponseRankingTests()
        {
            // TODO uncomment below to create an instance of RankingByCategoryResponseRanking
            //instance = new RankingByCategoryResponseRanking();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RankingByCategoryResponseRanking
        /// </summary>
        [Fact]
        public void RankingByCategoryResponseRankingInstanceTest()
        {
            // TODO uncomment below to test "IsType" RankingByCategoryResponseRanking
            //Assert.IsType<RankingByCategoryResponseRanking>(instance);
        }


        /// <summary>
        /// Test the property 'No'
        /// </summary>
        [Fact]
        public void NoTest()
        {
            // TODO unit test for the property 'No'
        }
        /// <summary>
        /// Test the property 'Trend'
        /// </summary>
        [Fact]
        public void TrendTest()
        {
            // TODO unit test for the property 'Trend'
        }
        /// <summary>
        /// Test the property 'AverageRanking'
        /// </summary>
        [Fact]
        public void AverageRankingTest()
        {
            // TODO unit test for the property 'AverageRanking'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }
        /// <summary>
        /// Test the property 'CurrentPrice'
        /// </summary>
        [Fact]
        public void CurrentPriceTest()
        {
            // TODO unit test for the property 'CurrentPrice'
        }
        /// <summary>
        /// Test the property 'ChangeRatio'
        /// </summary>
        [Fact]
        public void ChangeRatioTest()
        {
            // TODO unit test for the property 'ChangeRatio'
        }
        /// <summary>
        /// Test the property 'CurrentPriceTime'
        /// </summary>
        [Fact]
        public void CurrentPriceTimeTest()
        {
            // TODO unit test for the property 'CurrentPriceTime'
        }
        /// <summary>
        /// Test the property 'ChangePercentage'
        /// </summary>
        [Fact]
        public void ChangePercentageTest()
        {
            // TODO unit test for the property 'ChangePercentage'
        }

    }

}
