/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RankingByTradeVolumeResponseRanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RankingByTradeVolumeResponseRankingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RankingByTradeVolumeResponseRanking
        //private RankingByTradeVolumeResponseRanking instance;

        public RankingByTradeVolumeResponseRankingTests()
        {
            // TODO uncomment below to create an instance of RankingByTradeVolumeResponseRanking
            //instance = new RankingByTradeVolumeResponseRanking();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RankingByTradeVolumeResponseRanking
        /// </summary>
        [Fact]
        public void RankingByTradeVolumeResponseRankingInstanceTest()
        {
            // TODO uncomment below to test "IsType" RankingByTradeVolumeResponseRanking
            //Assert.IsType<RankingByTradeVolumeResponseRanking>(instance);
        }


        /// <summary>
        /// Test the property 'No'
        /// </summary>
        [Fact]
        public void NoTest()
        {
            // TODO unit test for the property 'No'
        }
        /// <summary>
        /// Test the property 'Trend'
        /// </summary>
        [Fact]
        public void TrendTest()
        {
            // TODO unit test for the property 'Trend'
        }
        /// <summary>
        /// Test the property 'AverageRanking'
        /// </summary>
        [Fact]
        public void AverageRankingTest()
        {
            // TODO unit test for the property 'AverageRanking'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'SymbolName'
        /// </summary>
        [Fact]
        public void SymbolNameTest()
        {
            // TODO unit test for the property 'SymbolName'
        }
        /// <summary>
        /// Test the property 'CurrentPrice'
        /// </summary>
        [Fact]
        public void CurrentPriceTest()
        {
            // TODO unit test for the property 'CurrentPrice'
        }
        /// <summary>
        /// Test the property 'ChangeRatio'
        /// </summary>
        [Fact]
        public void ChangeRatioTest()
        {
            // TODO unit test for the property 'ChangeRatio'
        }
        /// <summary>
        /// Test the property 'RapidTradePercentage'
        /// </summary>
        [Fact]
        public void RapidTradePercentageTest()
        {
            // TODO unit test for the property 'RapidTradePercentage'
        }
        /// <summary>
        /// Test the property 'TradingVolume'
        /// </summary>
        [Fact]
        public void TradingVolumeTest()
        {
            // TODO unit test for the property 'TradingVolume'
        }
        /// <summary>
        /// Test the property 'CurrentPriceTime'
        /// </summary>
        [Fact]
        public void CurrentPriceTimeTest()
        {
            // TODO unit test for the property 'CurrentPriceTime'
        }
        /// <summary>
        /// Test the property 'ChangePercentage'
        /// </summary>
        [Fact]
        public void ChangePercentageTest()
        {
            // TODO unit test for the property 'ChangePercentage'
        }
        /// <summary>
        /// Test the property 'ExchangeName'
        /// </summary>
        [Fact]
        public void ExchangeNameTest()
        {
            // TODO unit test for the property 'ExchangeName'
        }
        /// <summary>
        /// Test the property 'CategoryName'
        /// </summary>
        [Fact]
        public void CategoryNameTest()
        {
            // TODO unit test for the property 'CategoryName'
        }

    }

}
