/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestToken
        //private RequestToken instance;

        public RequestTokenTests()
        {
            // TODO uncomment below to create an instance of RequestToken
            //instance = new RequestToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestToken
        /// </summary>
        [Fact]
        public void RequestTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestToken
            //Assert.IsType<RequestToken>(instance);
        }


        /// <summary>
        /// Test the property 'APIPassword'
        /// </summary>
        [Fact]
        public void APIPasswordTest()
        {
            // TODO unit test for the property 'APIPassword'
        }

    }

}
