/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestSendOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestSendOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestSendOrder
        //private RequestSendOrder instance;

        public RequestSendOrderTests()
        {
            // TODO uncomment below to create an instance of RequestSendOrder
            //instance = new RequestSendOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestSendOrder
        /// </summary>
        [Fact]
        public void RequestSendOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestSendOrder
            //Assert.IsType<RequestSendOrder>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Fact]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'SecurityType'
        /// </summary>
        [Fact]
        public void SecurityTypeTest()
        {
            // TODO unit test for the property 'SecurityType'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Fact]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'CashMargin'
        /// </summary>
        [Fact]
        public void CashMarginTest()
        {
            // TODO unit test for the property 'CashMargin'
        }
        /// <summary>
        /// Test the property 'MarginTradeType'
        /// </summary>
        [Fact]
        public void MarginTradeTypeTest()
        {
            // TODO unit test for the property 'MarginTradeType'
        }
        /// <summary>
        /// Test the property 'DelivType'
        /// </summary>
        [Fact]
        public void DelivTypeTest()
        {
            // TODO unit test for the property 'DelivType'
        }
        /// <summary>
        /// Test the property 'FundType'
        /// </summary>
        [Fact]
        public void FundTypeTest()
        {
            // TODO unit test for the property 'FundType'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
        /// <summary>
        /// Test the property 'ClosePositionOrder'
        /// </summary>
        [Fact]
        public void ClosePositionOrderTest()
        {
            // TODO unit test for the property 'ClosePositionOrder'
        }
        /// <summary>
        /// Test the property 'ClosePositions'
        /// </summary>
        [Fact]
        public void ClosePositionsTest()
        {
            // TODO unit test for the property 'ClosePositions'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'ExpireDay'
        /// </summary>
        [Fact]
        public void ExpireDayTest()
        {
            // TODO unit test for the property 'ExpireDay'
        }
        /// <summary>
        /// Test the property 'FrontOrderType'
        /// </summary>
        [Fact]
        public void FrontOrderTypeTest()
        {
            // TODO unit test for the property 'FrontOrderType'
        }

    }

}
