/*
 * kabuステーションAPI
 *
 * # 定義情報   REST APIのコード一覧、エンドポイントは下記リンク参照     - [REST APIコード一覧](../ptal/error.html)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestSendOrderReverseLimitOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestSendOrderReverseLimitOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestSendOrderReverseLimitOrder
        //private RequestSendOrderReverseLimitOrder instance;

        public RequestSendOrderReverseLimitOrderTests()
        {
            // TODO uncomment below to create an instance of RequestSendOrderReverseLimitOrder
            //instance = new RequestSendOrderReverseLimitOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestSendOrderReverseLimitOrder
        /// </summary>
        [Fact]
        public void RequestSendOrderReverseLimitOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestSendOrderReverseLimitOrder
            //Assert.IsType<RequestSendOrderReverseLimitOrder>(instance);
        }


        /// <summary>
        /// Test the property 'TriggerSec'
        /// </summary>
        [Fact]
        public void TriggerSecTest()
        {
            // TODO unit test for the property 'TriggerSec'
        }
        /// <summary>
        /// Test the property 'TriggerPrice'
        /// </summary>
        [Fact]
        public void TriggerPriceTest()
        {
            // TODO unit test for the property 'TriggerPrice'
        }
        /// <summary>
        /// Test the property 'UnderOver'
        /// </summary>
        [Fact]
        public void UnderOverTest()
        {
            // TODO unit test for the property 'UnderOver'
        }
        /// <summary>
        /// Test the property 'AfterHitOrderType'
        /// </summary>
        [Fact]
        public void AfterHitOrderTypeTest()
        {
            // TODO unit test for the property 'AfterHitOrderType'
        }
        /// <summary>
        /// Test the property 'AfterHitPrice'
        /// </summary>
        [Fact]
        public void AfterHitPriceTest()
        {
            // TODO unit test for the property 'AfterHitPrice'
        }

    }

}
