/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RequestSendOrderDeriv
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestSendOrderDerivTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestSendOrderDeriv
        //private RequestSendOrderDeriv instance;

        public RequestSendOrderDerivTests()
        {
            // TODO uncomment below to create an instance of RequestSendOrderDeriv
            //instance = new RequestSendOrderDeriv();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestSendOrderDeriv
        /// </summary>
        [Fact]
        public void RequestSendOrderDerivInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestSendOrderDeriv
            //Assert.IsType<RequestSendOrderDeriv>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Fact]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'TradeType'
        /// </summary>
        [Fact]
        public void TradeTypeTest()
        {
            // TODO unit test for the property 'TradeType'
        }
        /// <summary>
        /// Test the property 'TimeInForce'
        /// </summary>
        [Fact]
        public void TimeInForceTest()
        {
            // TODO unit test for the property 'TimeInForce'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Fact]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
        /// <summary>
        /// Test the property 'ClosePositionOrder'
        /// </summary>
        [Fact]
        public void ClosePositionOrderTest()
        {
            // TODO unit test for the property 'ClosePositionOrder'
        }
        /// <summary>
        /// Test the property 'ClosePositions'
        /// </summary>
        [Fact]
        public void ClosePositionsTest()
        {
            // TODO unit test for the property 'ClosePositions'
        }
        /// <summary>
        /// Test the property 'FrontOrderType'
        /// </summary>
        [Fact]
        public void FrontOrderTypeTest()
        {
            // TODO unit test for the property 'FrontOrderType'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'ExpireDay'
        /// </summary>
        [Fact]
        public void ExpireDayTest()
        {
            // TODO unit test for the property 'ExpireDay'
        }

    }

}
