/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletMarginSuccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletMarginSuccessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletMarginSuccess
        //private WalletMarginSuccess instance;

        public WalletMarginSuccessTests()
        {
            // TODO uncomment below to create an instance of WalletMarginSuccess
            //instance = new WalletMarginSuccess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletMarginSuccess
        /// </summary>
        [Fact]
        public void WalletMarginSuccessInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletMarginSuccess
            //Assert.IsType<WalletMarginSuccess>(instance);
        }


        /// <summary>
        /// Test the property 'MarginAccountWallet'
        /// </summary>
        [Fact]
        public void MarginAccountWalletTest()
        {
            // TODO unit test for the property 'MarginAccountWallet'
        }
        /// <summary>
        /// Test the property 'DepositkeepRate'
        /// </summary>
        [Fact]
        public void DepositkeepRateTest()
        {
            // TODO unit test for the property 'DepositkeepRate'
        }
        /// <summary>
        /// Test the property 'ConsignmentDepositRate'
        /// </summary>
        [Fact]
        public void ConsignmentDepositRateTest()
        {
            // TODO unit test for the property 'ConsignmentDepositRate'
        }
        /// <summary>
        /// Test the property 'CashOfConsignmentDepositRate'
        /// </summary>
        [Fact]
        public void CashOfConsignmentDepositRateTest()
        {
            // TODO unit test for the property 'CashOfConsignmentDepositRate'
        }

    }

}
