/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WalletOptionSuccess
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WalletOptionSuccessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WalletOptionSuccess
        //private WalletOptionSuccess instance;

        public WalletOptionSuccessTests()
        {
            // TODO uncomment below to create an instance of WalletOptionSuccess
            //instance = new WalletOptionSuccess();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletOptionSuccess
        /// </summary>
        [Fact]
        public void WalletOptionSuccessInstanceTest()
        {
            // TODO uncomment below to test "IsType" WalletOptionSuccess
            //Assert.IsType<WalletOptionSuccess>(instance);
        }


        /// <summary>
        /// Test the property 'OptionBuyTradeLimit'
        /// </summary>
        [Fact]
        public void OptionBuyTradeLimitTest()
        {
            // TODO unit test for the property 'OptionBuyTradeLimit'
        }
        /// <summary>
        /// Test the property 'OptionSellTradeLimit'
        /// </summary>
        [Fact]
        public void OptionSellTradeLimitTest()
        {
            // TODO unit test for the property 'OptionSellTradeLimit'
        }
        /// <summary>
        /// Test the property 'MarginRequirement'
        /// </summary>
        [Fact]
        public void MarginRequirementTest()
        {
            // TODO unit test for the property 'MarginRequirement'
        }

    }

}
