/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing InfoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InfoApiTests : IDisposable
    {
        private InfoApi instance;

        public InfoApiTests()
        {
            instance = new InfoApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InfoApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InfoApi
            //Assert.IsType<InfoApi>(instance);
        }

        /// <summary>
        /// Test BoardSymbolexchangeGet
        /// </summary>
        [Fact]
        public void BoardSymbolexchangeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //string symbol = null;
            //string exchange = null;
            //var response = instance.BoardSymbolexchangeGet(X_API_KEY, symbol, exchange);
            //Assert.IsType<BoardSuccess>(response);
        }

        /// <summary>
        /// Test OrdersGet
        /// </summary>
        [Fact]
        public void OrdersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //string product = null;
            //var response = instance.OrdersGet(X_API_KEY, product);
            //Assert.IsType<List<Object>>(response);
        }

        /// <summary>
        /// Test PositionsGet
        /// </summary>
        [Fact]
        public void PositionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //string product = null;
            //var response = instance.PositionsGet(X_API_KEY, product);
            //Assert.IsType<List<Object>>(response);
        }

        /// <summary>
        /// Test SymbolSymbolexchangeGet
        /// </summary>
        [Fact]
        public void SymbolSymbolexchangeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //string symbol = null;
            //string exchange = null;
            //var response = instance.SymbolSymbolexchangeGet(X_API_KEY, symbol, exchange);
            //Assert.IsType<SymbolSuccess>(response);
        }
    }
}
