/*
 * kabuステーションAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing WalletApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WalletApiTests : IDisposable
    {
        private WalletApi instance;

        public WalletApiTests()
        {
            instance = new WalletApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WalletApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WalletApi
            //Assert.IsType<WalletApi>(instance);
        }

        /// <summary>
        /// Test WalletCashGet
        /// </summary>
        [Fact]
        public void WalletCashGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //var response = instance.WalletCashGet(X_API_KEY);
            //Assert.IsType<WalletCashSuccess>(response);
        }

        /// <summary>
        /// Test WalletCashSymbolexchangeGet
        /// </summary>
        [Fact]
        public void WalletCashSymbolexchangeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //string symbol = null;
            //string exchange = null;
            //var response = instance.WalletCashSymbolexchangeGet(X_API_KEY, symbol, exchange);
            //Assert.IsType<WalletCashSuccess>(response);
        }

        /// <summary>
        /// Test WalletMarginGet
        /// </summary>
        [Fact]
        public void WalletMarginGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //var response = instance.WalletMarginGet(X_API_KEY);
            //Assert.IsType<WalletMarginSuccess>(response);
        }

        /// <summary>
        /// Test WalletMarginSymbolexchangeGet
        /// </summary>
        [Fact]
        public void WalletMarginSymbolexchangeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string X_API_KEY = null;
            //string symbol = null;
            //string exchange = null;
            //var response = instance.WalletMarginSymbolexchangeGet(X_API_KEY, symbol, exchange);
            //Assert.IsType<WalletMarginSuccess>(response);
        }
    }
}
